### ISSUE TITLE
Storefront UI hangs at Pay and Confirm

### ISSUE THREAD

**Issue by BLR-0118** [beckn/biab-storefront-ui#121]
Storefront UI hangs at "Pay and Confirm" step of the order flow. Behaviour consistent across Chrome (web, mobile), Edge, Firefox.

Steps: 
1. Open http://ec2-3-110-48-23.ap-south-1.compute.amazonaws.com:8080/
2. Enter location "Bengaluru" and search for "banana"
3. Add 1st item to cart, view cart & checkout
4. Enter and save shipping details, click "Proceed to pay"
5. Select "Cash on Delivery" and click on "Pay & Confirm"
The app hangs

**Comment by BLR-0118** [comment]
Video link - https://watch.screencastify.com/v/3kVxklvYPuorPb0bwWEU

**Comment by BLR-0118** [comment]
@techframewirk

**Comment by techframewirk** [comment]
@BLR-0118 can you try giving a landmark in the address section as well and let us know if it works? We will be removing the optional marker for this.

**Comment by BLR-0118** [comment]
@techframewirk yes, works with landmark. Should I keep this open until you remove the optional marker?

**Comment by techframewirk** [comment]
@BLR-0118 Yes let's keep this open.

**Comment by techframewirk** [comment]
Closing this issue as this change has been merged and present in the QA environment.
