### ISSUE TITLE
Init Failed in Reference BAP

### ISSUE THREAD

**Issue by SherinShafa27** [beckn/biab-storefront-ui#123]
In init endpoint, getting error in reference BAP while clicking the proceed to Pay button, the error response says it "BPP returned error" but this request doesn't even reach our server
![image](https://user-images.githubusercontent.com/95422888/144432476-dbee6cf0-8e26-4ed0-80f8-d55c132ccd96.png)
{
    "status": 500,
    "response": {
        "req": {
            "method": "POST",
            "url": "http://ec2-3-108-236-16.ap-south-1.compute.amazonaws.com:9001/client/v1/initialize_order",
            "data": {
                "context": {
                    "transaction_id": "946ce2d8-94db-4a5e-8e1d-6bfd055d9deb"
                },
                "message": {
                    "items": [
                        {
                            "id": "5334-Shopify-1-2",
                            "quantity": {
                                "count": 1
                            },
                            "bpp_id": "integration-qa.gofrugalretail.com/ecommerce/ondc",
                            "provider": {
                                "id": "Ecommsherin",
                                "locations": [
                                    null
                                ]
                            }
                        }
                    ],
                    "billing_info": {
                        "address": {
                            "door": "chennai",
                            "country": "IND",
                            "city": "Waimea",
                            "street": "N/A, Premier Nagar, Othakalmandapam",
                            "area_code": "641032",
                            "state": "Hawaii",
                            "building": "2/3"
                        },
                        "phone": "9898989898",
                        "name": "Akilan",
                        "email": ""
                    },
                    "delivery_info": {
                        "type": "HOME-DELIVERY",
                        "name": "Akilan",
                        "phone": "9898989898",
                        "email": "",
                        "location": {
                            "address": {
                                "door": "chennai",
                                "country": "IND",
                                "city": "Waimea",
                                "street": "N/A, Premier Nagar, Othakalmandapam",
                                "area_code": "641032",
                                "state": "Hawaii",
                                "building": "2/3"
                            },
                            "gps": "12.9063433,77.5856825"
                        }
                    }
                }
            },
            "headers": {
                "content-type": "application/json"
            }
        },
        "header": {
            "vary": "Origin, Access-Control-Request-Method, Access-Control-Request-Headers",
            "x-content-type-options": "nosniff",
            "x-xss-protection": "1; mode=block",
            "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
            "pragma": "no-cache",
            "expires": "0",
            "x-frame-options": "DENY",
            "content-type": "application/json",
            "transfer-encoding": "chunked",
            "date": "Thu, 02 Dec 2021 06:31:18 GMT",
            "connection": "close"
        },
        "status": 500,
        "text": "{\"context\":{\"domain\":\"nic2004:52110\",\"country\":\"IND\",\"city\":\"std:080\",\"action\":\"init\",\"core_version\":\"0.9.1\",\"bap_id\":\"ec2-3-108-236-16.ap-south-1.compute.amazonaws.com\",\"bap_uri\":\"http://ec2-3-108-236-16.ap-south-1.compute.amazonaws.com:9002/protocol/v1\",\"transaction_id\":\"946ce2d8-94db-4a5e-8e1d-6bfd055d9deb\",\"message_id\":\"327b050b-6bc7-4b55-b3f4-2bae35065715\",\"timestamp\":\"2021-12-02T06:31:17.977752Z\"},\"message\":{\"ack\":{\"status\":\"NACK\"}},\"error\":{\"code\":\"BAP_011\",\"message\":\"BPP returned error\"}}"
    }
}

**Comment by BLR-0118** [comment]
@techframewirk

**Comment by techframewirk** [comment]
Hi @SherinShafa27 Can you share the on_search and on_select JSONs returned by the BPP?

**Comment by SherinShafa27** [comment]
> Hi @SherinShafa27 Can you share the on_search and on_select JSONs returned by the BPP?

[on_searchh.txt](https://github.com/beckn/biab-storefront-ui/files/7659982/on_searchh.txt)
[on_select_kitkat.txt](https://github.com/beckn/biab-storefront-ui/files/7659987/on_select_kitkat.txt)

**Comment by techframewirk** [comment]
Hi @SherinShafa27 I have asked Akilan to add provider and provider_location in on_select as per [0.9.3-draft](https://github.com/beckn/protocol-specifications/blob/core-0.9.3-draft/core/v0/api/core.yaml) version of the spec that the reference BAP uses. Please let us know if that helped.

**Comment by SherinShafa27** [comment]
@techframewirk  we have added as yu mentioned but still facing the same issue in init.Sharing the response of on_select below {"context":{"domain":"nic2004:52110","country":"IND","city":"std:080","action":"search","core_version":"0.9.1","bap_id":"ec2-3-108-236-16.ap-south-1.compute.amazonaws.com","bap_uri":"http://ec2-3-108-236-16.ap-south-1.compute.amazonaws.com:9002/protocol/v1","transaction_id":"dbefb21a-32d1-486c-a17d-7f18fe32ee61","message_id":"22ccd458-ce82-4b09-8ee2-373aa18186ea","timestamp":"2021-12-09T10:06:38.859007Z"},"message":{"quote":{"provider":{"id":"5466-WooCommerce-1-3028"},"provider_location":{"id":"5466-WooCommerce-1-3028","gps":"13.08784, 80.27847"},"items":[{"id":"5466-WooCommerce-1-1","price":{"currency":"INR","value":"100.0"},"quantity":{"selected":{"count":2}}}],"quote":{"price":{"currency":"INR","value":"200.0"},"breakup":[{"title":"KIT KAT","price":{"currency":"INR","value":"200.0"}}]}}}}

**Comment by techframewirk** [comment]
@SherinShafa27 It is message.order not message.quote. Please refer to the specifications [here](https://github.com/beckn/protocol-specifications/blob/core-0.9.3-draft/core/v0/api/core.yaml).

**Comment by SherinShafa27** [comment]
@techframewirk actually we are sending the same only to BAP

**Comment by techframewirk** [comment]
@SherinShafa27 Can you remove items array from the order.provider object and try once? It is already present in order.items.

**Comment by SherinShafa27** [comment]
@techframewirk yes removed as you suggested. still reference BAP APP throwing 500 <html>
<body>


{"context":{"domain":"nic2004:52110","country":"IND","city":"std:080","action":"on_select","core_version":"0.9.1","bap_id":"ec2-3-108-236-16.ap-south-1.compute.amazonaws.com","bap_uri":"http://ec2-3-108-236-16.ap-south-1.compute.amazonaws.com:9002/protocol/v1","bpp_id":"integration-qa.gofrugalretail.com/ecommerce/ondc","bpp_uri":"https://integration-qa.gofrugalretail.com/ecommerce/ondc","transaction_id":"0ee9f293-780a-403c-88a0-8242bcf9a770","message_id":"968b3f1b-221e-42e2-aa6a-3201bd70d424","timestamp":"2021-12-13T05:58:33.270Z"},"message":{"order":{"provider":{"id":"5236-WooCommerce-1-2824"},"provider_location":{"id":"5236-WooCommerce-1-2824","gps":"13.08784, 80.27847"},"items":[{"id":"5236-WooCommerce-1-31U38","price":{"currency":"IND","value":50.0},"quantity":{"selected":{"count":1}}}],"quote":{"price":{"currency":"IND","value":50.0},"breakup":[{"title":"Choco Brownie","price":{"currency":"IND","value":50.0}}]}}}}
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by techframewirk** [comment]
@SherinShafa27 Can you trigger one more request and share the transaction_id?

**Comment by techframewirk** [comment]
@SherinShafa27 As discussed please confirm if adding location_id to the item object helped to solve this issue.

**Comment by SherinShafa27** [comment]
yes @techframewirk after adding location_id,we got init request from reference BAP App
