### ISSUE TITLE
{'ack': {'status': 'NACK'}}, 'error': {'code': 'BAP_006', 'message': 'Error when writing to DB'}   

### ISSUE THREAD

**Issue by VidyaGF** [beckn/biab-storefront-ui#125]
"Getting the following message post on_search, on_select, on_init, on_confirm . 
message': {'ack': {'status': 'NACK'}}, 'error': {'code': 'BAP_006', 'message': 'Error when writing to DB'}   

Still the items are displayed, but not sure what it means . "

**Comment by BLR-0118** [comment]
@techframewirk

**Comment by techframewirk** [comment]
@VidyaGF  Can you check if you are still getting NACK?

**Comment by techframewirk** [comment]
Closing as no response in 7 days.
