### ISSUE TITLE
quote and fulfillment.start is not received in the json received from BAP

### ISSUE THREAD

**Issue by VidyaGF** [beckn/biab-storefront-ui#127]
quote and fulfillment.start is not received in the json for confirm endpoint as given in the example, 
https://slack-files.com/T3RVDDPRT-F02N3NJT2G6-4324633428

**Comment by BLR-0118** [comment]
@techframewirk

**Comment by techframewirk** [comment]
Hi @VidyaGF Since the quote is an object created by the BPP, the BAP can choose not to send it again. In this case wouldn't fulfillment.start be the store location which is also something from the BPP?

**Comment by SandeepGF** [comment]
@techframewirk  Ok noted
