### ISSUE TITLE
billing and fullfillment details in on_init () response

### ISSUE THREAD

**Issue by VidyaGF** [beckn/biab-storefront-ui#128]
If we need to send the billing and fullfillment details in on_init () response , We will need to get it in init() call as well. Currently , in the sample jsons ,we have two separate usecase for billing and fullfillment. We dont see both fields everytime

**Comment by BLR-0118** [comment]
@techframewirk

**Comment by techframewirk** [comment]
Hi @VidyaGF Can you share the link of those use case jsons (or use case names in case of sandbox) so that I can check?

**Comment by SandeepGF** [comment]
@techframewirk  please find the link below
Share Billing details
https://drive.google.com/file/d/1dsJR4t_BI1fkqFm_nix-jEgcgmXPMgLI/view

Return updated quote with payment terms
https://drive.google.com/file/d/1lfZKDJoFS9nbIUJ_kAH-9nv1HrH-lXn4/view+

**Comment by techframewirk** [comment]
Hi Vidya this would be clarified based on the mandatory fields that are required for a specific network.
