### ISSUE TITLE
No mock Delivery BPP

### ISSUE THREAD

**Issue by VidyaGF** [beckn/biab-storefront-ui#129]
There is currently no mock BPP in delivery to test the flow

**Comment by BLR-0118** [comment]
Talked to Mahesh of Goodbox today morning. He's upgrading the protocol spec and then will integrate the delivery bpp with the registry. Expected closure is EOD tomorrow (7/12)

**Comment by techframewirk** [comment]
Since this is not an issue related to BIAB BAP closing the same. Thanks.
