### ISSUE TITLE
Reference BAP App is hanged after Proceed to Pay

### ISSUE THREAD

**Issue by SherinShafa27** [beckn/biab-storefront-ui#133]
After we send on_init response,unable to proceed in reference BAP as its loading still.Attaching screenshot and BPP on_init response for reference.We are sending single response only but showing multiple responses in the reference App.
![Screenshot (361)](https://user-images.githubusercontent.com/95422888/146191161-aaa8b675-64af-4167-8449-17ed85ac3c6f.png)

{"context":{"domain":"nic2004:52110","country":"IND","city":"std:080","action":"on_init","core_version":"0.9.1","bap_id":"ec2-3-108-236-16.ap-south-1.compute.amazonaws.com","bap_uri":"http://ec2-3-108-236-16.ap-south-1.compute.amazonaws.com:9002/protocol/v1","bpp_id":"integration-qa.gofrugalretail.com/ecommerce/ondc","bpp_uri":"https://integration-qa.gofrugalretail.com/ecommerce/ondc","transaction_id":"3a2c20af-b981-423a-999f-a625ceeb154d","message_id":"a946d863-5711-490b-ac2a-545b2fdb0026","timestamp":"2021-12-15T12:49:48.635185Z"},"message":{"order":{"items":[{"id":"5466-WooCommerce-1-16","price":{"currency":"IND","value":110.0},"quantity":{"count":1}}],"billing":{"name":"Sherin","address":{"door":"hhh","building":"kk nagar","street":"32,swami street","city":"Chennai","state":"Tamil Nadu","country":"IND","area_code":"600001"},"email":"","phone":"7904741400"},"fulfillment":{"type":"HOME-DELIVERY","provider_id":"5466-WooCommerce-1","tracking":false,"customer":{"person":{"name":"Sherin"}},"end":{"location":{"gps":"12.9063433,77.5856825","address":{"door":"hhh","building":"kk nagar","street":"32,swami street","city":"Chennai","state":"Tamil Nadu","country":"IND","area_code":"600001"}},"contact":{"phone":"7904741400","email":""}}},"quote":{"price":{"currency":"IND","value":110.0},"breakup":[{"title":"DARK FANTASY","price":{"currency":"IND","value":110.0}}]},"payment":{"uri":"https://gofrugal-payment-gateway.com/pay","tl_method":"POST","params":{"transaction_id":"3a2c20af-b981-423a-999f-a625ceeb154d","amount":"110.0","mode":"CASH ON DELIVERY","vpa":"https://integration-qa.gofrugalretail.com/ecommerce/ondc@upi"},"type":"ON-ORDER","status":"NOT-PAID"}}}}

**Comment by techframewirk** [comment]
HI @SherinShafa27 As per the [protocol specifications](https://github.com/beckn/protocol-specifications) payment.tl_method should be either `http/get` or `http/post`.

**Comment by BLR-0118** [comment]
@techframewirk also, currency should be "INR", not "IND", right?

**Comment by techframewirk** [comment]
@BLR-0118 Yes!

**Comment by SherinShafa27** [comment]
@techframewirk/ @BLR-0118  we have send currency as "INR" only after comparing with falcon's response we changed like that. Will revert that change on currency

**Comment by SherinShafa27** [comment]
After chnaging tl_method,we got confirm request.Hence closing the issue
