### ISSUE TITLE
Getting 400 for on_confirm endpoint

### ISSUE THREAD

**Issue by SherinShafa27** [beckn/biab-storefront-ui#136]
Getting 400 for on_confirm endpoint.May i know the reason for this?? <html>
<body>

{"context":{"domain":"nic2004:52110","country":"IND","city":"std:080","action":"on_confirm","core_version":"0.9.1","bap_id":"ec2-3-108-236-16.ap-south-1.compute.amazonaws.com","bap_uri":"http://ec2-3-108-236-16.ap-south-1.compute.amazonaws.com:9002/protocol/v1","bpp_id":"integration-qa.gofrugalretail.com/ecommerce/ondc","bpp_uri":"https://integration-qa.gofrugalretail.com/ecommerce/ondc","transaction_id":"fc889453-bf9b-49a9-9dc0-b6bc7b79e2fa","message_id":"c484bf07-67b6-4808-8669-0f039b04357a","timestamp":"2021-12-16T10:36:26.019738Z"},"message":{"order":{"items":[{"id":"5466-WooCommerce-1-1","quantity":{"count":1}}],"offers":[],"billing":{"name":"Nazii sha","address":{"door":"hcjs","building":"kkk nagar","street":"22","city":"Chennai","state":"Tamil Nadu","country":"IND","area_code":"600001"},"email":"","phone":"7799221100"},"fulfillment":{"type":"home_delivery","provider_id":"5466-WooCommerce-1","tracking":false,"customer":{"person":{"name":"Nazii sha"}},"end":{"location":{"gps":"12.9063433,77.5856825","address":{"door":"hcjs","building":"kkk nagar","street":"22","city":"Chennai","state":"Tamil Nadu","country":"IND","area_code":"600001"}},"contact":{"phone":"7799221100","email":""}}},"id":"5466-WooCommerce-1-8","quote":{"price":{"currency":"INR","value":100.0},"breakup":[{"title":"KIT KAT","price":{"currency":"INR","value":100.0}}]},"state":"ACTIVE","payment":{"params":{"amount":"100.0"},"status":"PAID"},"add_ons":[],"updated_at":"16/12/2021_10:36:26"}}}
--

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by techframewirk** [comment]
"updated_at":"16/12/2021_10:36:26" is not as per RFC3339 format. Please make it the same as you have for timestamp in context.

**Comment by SherinShafa27** [comment]
yes it worked
